FROM rabbitmq:3-management

# (Optional) Copy your custom definitions/configuration
# COPY rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
# COPY definitions.json /etc/rabbitmq/definitions.json

# (Optional) Enable or configure plugins, users, etc.
# RUN rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_stomp

# Expose necessary ports
EXPOSE 5672 15672
